title: Jinning Liang
email: jinningliangastro@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username: JinningLianggithub

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Site settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
